### ISSUE TITLE
Planned release date

### ISSUE THREAD

**Issue by juanmed** [Banconxuan/RTM3D#1]
Hi,

I was wondering when is the planned date for the release of your code? Your paper is quite interesting and wanted to reproduce the results.

Thanks

**Comment by Banconxuan** [comment]
I am currently spending the Chinese New Year in wuhan city, China. Due to the impact of the new coronavirus, the city of wuhan has shut down public transportation, and I'll be stuck here until the virus is contained. The server of our lab also has been suspended, so I cannot access the original program. But I promise I'll upload the code as soon as I get back to the lab. In the meantime, you can try to reproduce our paper. Much of the code for this paper is based on centernet, so we believe this can be easily replicated.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Juan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 晚上10:52
收件人:&nbsp;"Banconxuan/RTM3D"<RTM3D@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Banconxuan/RTM3D] Planned release date (#1)




Hi,
 
I was wondering when is the planned date for the release of your code? Your paper is quite interesting and wanted to reproduce the results.
 
Thanks

**Comment by juanmed** [comment]
Oh wow, I did not expected you to be in such a difficult situation. Thanks for your answer and I hope this situation ends soon for all the people over there.

**Comment by litingsjj** [comment]
Did you have plan to release your code?
